version: "3.3"
services:
  backend:
    build: ./backend
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL=postgres://admin:dupa123@db:5432/something
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001
    depends_on:
      - db
  db:
    image: postgres:15.1
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dupa123
      - POSTGRES_DB=something
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
